### ISSUE TITLE
cascade (was: swichTo)

### ISSUE THREAD

**Issue by fpillet** [RxSwiftCommunity/RxSwift-Ext#13]
### Name and description

`switchTo(other : Observable<E>)`

this operator will send all elements emitted by the source observable until the `other` observable starts emitting elements, at which point only elements emitted by `other` will be considered.

may need an additional optional flag to control whether the resulting observable completes when any of `self` and / or `other` completes

### Motivation for inclusion

Allows subscribing to multiple sequences but irrevocably switching to the next when it starts emitting. This use case doesn't seem to be covered by any existing Rx operator.

### Suggested implementation

```swift
extension ObservableType {
    func switchTo(other: Observable<E>) -> Observable<E> {
        return Observable.create { observer in
            let a = self.asObservable().subscribe(observer)
            let b = other.subscribe { (event) in
                a.dispose()
                observer.on(event)
            }
            return AnonymousDisposable {
                a.dispose()
                b.dispose()
            }
        }
    }
}
```

**Comment by fpillet** [comment]
An idea came up re-reading this proposal:

`switchTo(other : Observable<E> ...)`

In other words, the behavior of the proposed `switchTo` but applied to any number of parameters (of course a variant with a `SequenceType` will be available.

I think this is an affordable generalization of the operator. Opinions? @dpassage ?

**Comment by dpassage** [comment]
Would the intent be that if _any_ of the arguments pop, switch to that one? Or would it be a cascade of sorts?

**Comment by fpillet** [comment]
I'm thinking about a cascade. Actually I was considering proposing the name `casadeTo`

**Comment by fpillet** [comment]
Actually hedging towards `cascade` as a name. This way we can seemlessly offer implementations that cascade an observable to any number of subsequent observables, and also offer a `Observable.cascade(obs : Observable<E> ...)` implementation with a coherent naming scheme

**Comment by fpillet** [comment]
In the same spirit, what about `cascadeTo` (`someObservable.cascadeTo(someOtherObservable)`) and `cascade` as a static function of `Observable`(`Observable.cascade(a, b, c)`)

**Comment by fpillet** [comment]
Implemented as `cascadeTo` and `Observable.cascade` in 972a1a5

**Comment by fpillet** [comment]
What's been done is not enough. One issue is that a later sequence can complete before earlier ones, and the resulting sequence may never complete. Also, we need locking. Improvements forthcoming.

**Comment by fpillet** [comment]
Done in 49281d8
