### ISSUE TITLE
Refine unwrap

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxSwift-Ext#2]
`unwrap` was included while we were drafting the repo structure as an example - I got to:
1) add more tests - test for values, edge cases
2) have another look at the code 
3) refine the playground example

I think it's important for this one to is the way we want the code to look lile since this is the first piece of code and others who PR would look at it for guidance how to structure their stuff (maybe?)

**Comment by sergdort** [comment]
Hi, guys correct me if I wrong :)

But I think it would be more understandable for [Optional](https://github.com/RxSwiftCommunity/RxSwift-Ext/blob/master/Source/unwrap.swift#L37) `isEmpty` to be 
```swift
    public func isEmpty() -> Bool {
        return self == nil
    }

```
rather then 
``` swift 
    public func isEmpty() -> Bool {
        return !(flatMap({_ in true})?.boolValue == true)
    }
```

**Comment by icanzilb** [comment]
@sergdort have you tried if the code you're proposing works?

**Comment by sergdort** [comment]
@icanzilb the tests are passing on my machine :)

**Comment by icanzilb** [comment]
ok I'll give it a try 👍

**Comment by icanzilb** [comment]
@sergdort thanks for the suggestion - I made the update to the code already 👍
