### ISSUE TITLE
Write a proper README.md with examples

### ISSUE THREAD

**Issue by fpillet** [RxSwiftCommunity/RxSwift-Ext#20]
Current readme is just a template, write one that lists the available operators and show some example of use

**Comment by thanegill** [comment]
Leaving this here, as @orta had a good idea for dynamically creating a README.

https://rxswift.slack.com/archives/community/p1462643004000682

**Comment by fpillet** [comment]
I started exploring ways of automatically producing the list of operators by the use of `SourceKitten` and the `jq` JSON parser. At this stage I think we could automatically craft a list with documentation -- been learning the jq query syntax, not fully up to speed with it yet

**Comment by fpillet** [comment]
Not up to speed with automated Readme production. I wrote one manually.

290b7c7
