### ISSUE TITLE
Distinct operator

### ISSUE THREAD

**Issue by sergdort** [RxSwiftCommunity/RxSwift-Ext#21]
### Name and description 
`distinct()`

[suppress duplicate items emitted by an Observable](http://reactivex.io/documentation/operators/distinct.html)
### Motivation for inclusion

We have some variants of `distinctUntilChanged` operator in the main repo, but do not have `distinct`, which is implemented for the most other languages which supports Rx.

### Proposed implementation

```swift
extension Observable where Element: Hashable {
   
   func distinct() -> Observable<Element> {
      var set = Set<Element>()
      return flatMap { element -> Observable<Element> in
         objc_sync_enter(self); defer {objc_sync_exit(self)}
         if set.contains(element) {
            return Observable<Element>.empty()
         } else {
            set.insert(element)
            return Observable<Element>.just(element)
         }
      }
   }
}
```

**Comment by icanzilb** [comment]
I'm just thinking aloud here - say if you're using this operator on an Observable<UIImage> wouldn't that consume a lot of memory very quickly? Since the element is a `Hashable` anyway (in your proposed code) isn't it better to store the hashes instead of the elements themselves?

**Comment by sergdort** [comment]
@icanzilb, I see your point.

But, I wonder if could be a case where `Observable` emits elements which  have a different type but they are related ? 
Kind of :
```
class A: Hashable {
}
class B: A {
}

let subject = PublishSubject<A>()

let distinct = subject.asObservable().distinct()

.....

subject.onNext(a)
subject.onNext(b) //so hash of  `b` is the same as hash of `a` but they are different
```

So in this case b would not be edited.

Or I missing something :)

**Comment by sergdort** [comment]
But, yeah potential memory problems is definitely a problem :(

**Comment by sergdort** [comment]
But if we talking about classes. Isn't `Set` will just hold strong reference to the object?

**Comment by icanzilb** [comment]
In your code you're adding the parameter to `Hashable` not to classes. And even if we limit the operator to classes I think this case will be even worse because adding the object to the set will eventually retain it, while it otherwise might have been released (in case nothing else retained the object of course). I think this

**Comment by icanzilb** [comment]
I can see this operator being totally useful, I'm just thinking of a way to have it without a) side effects (e.g. retaining the objects and b) optimal memory footprint (e.g. when the Observable is emitting structs)

**Comment by sergdort** [comment]
@icanzilb  I totally agree with you 

The only concern that I have is in this test case:

```swift
class A: Hashable, CustomStringConvertible {
   let a: Int
   
   init(a: Int) {
      self.a = a
   }
   
   var hashValue: Int {
      return a
   }
   
   func isEqual(other: A) -> Bool {
      return a == other.a && other.isEqual(self)
   }
   var description: String {
      return "\(self.dynamicType) a = \(a)"
   }
}

func == (lhs: A, rhs: A) -> Bool {
   return lhs.isEqual(rhs)
}

class B: A {
   let b: Int
   
   init(a: Int, b: Int) {
      self.b = b
      super.init(a: a)
   }
   
   override var hashValue: Int {
      return a + b
   }
   
   override var description: String {
      return super.description + " b = \(b)"
   }
   
   override func isEqual(other: A) -> Bool {
      if let otherB = other as? B {
         return a == otherB.a && b == otherB.b
      } else {
         return false
      }
   }
}

      let subject = PublishSubject<A>()
      subject.asObservable()
         .distinct()
         .subscribeNext {
            print($0)
         }
         .addDisposableTo(disposeBag)
      
      let a = A(a: 0)
      let b = B(a: 0, b: 0)
      
      subject.onNext(a)
      subject.onNext(b)
      subject.onCompleted()
```

As you can see in this case `hashValue` of `a` and `b` is the same (sure this is very bad design of `hashValue ` in the `B` class but equality of `hashValues` in any cases does not guaranty that objects are equal)

In this case if I would store hashes in the Set instead of a real object I would end up that `b` has not being emitted

**Comment by icanzilb** [comment]
My impression was `Set` also uses `hashValue` to determine the uniqueness of the objects. I'll research on that later on, need to do smth else right now

**Comment by fpillet** [comment]
Seems to me that we could provide several versions of this `distinct` operator:

- one that is generalized and requires elements to conform to the `Equatable` protocol. Would be the slowest implementation because it would have to compare all elements in a list until it finds one that is equal (or not)

- An implementation for the case where elements conform to `Hashable` and `Equatable`: we store elements in a set and `Hashable` guarantees faster lookups. Note that `Hashable` alone is not enough because the hash is not guaranteed to be unique -- it's just use to classify objects in smaller buckets.

So having elements conform to `Equatable` would be a bare minimum and would work but not provide the best performance. What do you guys think?

**Comment by sergdort** [comment]
Good point @fpillet !

I wonder if they are we could also have one version for `Comparable` and  always keep array sorted so we can use binary search? 
Or this is too much?

**Comment by fpillet** [comment]
That's another good idea although I'm not sure we need to go that far -- with `Hashable` and relying on standard Swift library implementation of `Set` we should be pretty good. But it's worth a shot with some performance comparison. In there is a gain, then yes it makes sense to have a third implementation!

**Comment by fpillet** [comment]
Ok so let's go with two implementations, and @sergdort if you think that we can get increased performance with a third implementation specializing on `Comparable`, please feel free to add it too
