### ISSUE TITLE
negate(Bool) -> Bool

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxSwift-Ext#3]
### negate

`negate()` negates a `Bool` value

Not sure if that's the best name for the op?

### Motivation for inclusion

Especially when working with UI you need to show/hide controls - the problem is that the same observable (let's say `shouldShowSearchBar`) will drive both the _visibility_ of a search and the fact that some buttons will **not** be hidden - I get to use that often and I think having a map {!$0} for each case gets very verbose.

### Example of usage

```swift
shouldShowSearchBar.bindTo(searchBar.rx_firstResponder) //true will make the bar first responder
shouldShowSearchBar.negate().bindTo(searchResults.rx_hidden) //true -> false will **unhide** the view
```

**Comment by icanzilb** [comment]
the operator could also work on `Observable<Int>` or `Observable<Double>` but I think this won't be a common use case, what do you guys think?

**Comment by fpillet** [comment]
ReactiveCocoa uses `not`, I think it's a better name

**Comment by thanegill** [comment]
Something like this?

```swift
extension ObservableType where E: BooleanType {
    /// Boolean not operator
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func not() -> Observable<Bool> {
        return self.map { value -> Bool in
            return !value
        }
    }
}

extension Driver where Element: BooleanType {
    /// Boolean not operator
    @warn_unused_result(message="http://git.io/rxs.uo")
    public func not() -> Driver<Bool> {
        return self.map { value -> Bool in
            return !value
        }
    }
}
```

**Comment by fpillet** [comment]
Perfect, care to push it to repo? Maybe send a PR, and we may need to put things in

**Comment by fpillet** [comment]
Oh BTW `Driver` is `RxCocoa` - We discussed doing a second repository (`RxCocoa+Ext`) for RxCocoa, so maybe the driver version should be left out for now

**Comment by thanegill** [comment]
Grr... This is where I wish there was some way to define operators that can be used on both Observable and Driver. But yeah I'll leave the Driver not operator out.

**Comment by fpillet** [comment]
The jury is not out on this. We can discuss it with @kzaher on the RxSwift Slack and see how we move forward. I can see how splitting things can be a pain, although we also need to think about the server side and people who do not include RxCocoa.

**Comment by thanegill** [comment]
It's somewhat out. https://github.com/ReactiveX/RxSwift/issues/496

I agree with everything that @kzaher said there. I don't think there is a better way than what's currently in place, especially if Driver is not the only Unit. Maybe there's some way to opt into operators, like a mixin or trait.

**Comment by icanzilb** [comment]
@thanegill will you find the time to do a PR with this operator?
