### ISSUE TITLE
mapTo(Any)

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxSwift-Ext#8]
### replaceWith(AnyObject)

maps any value to a constant

```swift
func replaceWith<R>(value: R) -> Observable<R> {
        return map { _ in value }
    }
```
### Motivation for inclusion

Sometimes I need to just replace whatever value an Observable emits with a given constant, often times I'll do that for buttons:

```swift
[btnPlay.rx_tap.map({_ in true}), btnStop.rx_tap.map({_ in false})].toObservable()
```

### Example of usage

```
[btnPlay.rx_tap.replaceWith(true), btnStop.rx_tap.replaceWith(false)].toObservable()
```

**Comment by fpillet** [comment]
The naming leaves me perplexed ... what about `mapTo` ?

**Comment by icanzilb** [comment]
To me personally `map` in the name would imply some mapping being done (which is still the case even if the input is being totally ignored). `replaceWith` better expressed the intention to completely ignore the input on my own code. That being said - I don't have any strong affections what the precise name of the operator will be. Maybe poll more ppls from rxswiftcommunity?

**Comment by esttorhe** [comment]
IMHO replace conveys to me more meaning for this specific operator than mapTo. 

I don't think mapTo is a bad choice just that to me specifically replace clicks better on my brain

**Comment by icanzilb** [comment]
looks like we're going with `mapTo`: https://github.com/ReactiveX/rxjs/blob/master/src/operator/mapTo.ts

**Comment by icanzilb** [comment]
https://github.com/RxSwiftCommunity/RxSwift-Ext/pull/12
