### ISSUE TITLE
Observable.serialize

### ISSUE THREAD

**Issue by phuna** [RxSwiftCommunity/RxSwift-Ext#9]
### Name of the operator
`Observable.serialize()`

### Motivation for inclusion
I'm new to Rx so I'm not really sure if this is a appropriate usage of ReactiveX's [serialize operator](http://reactivex.io/documentation/operators/serialize.html) or not. In my case I think it's useful because I need to create a bunch of HTTP requests in background then in response handler of each request I call `observer.on(.Next(element))`. In this case I want to ensure `onNext` will be delivered serially to subscriber.

### Example of usage
```swift
func download(urls: [String]) -> Observable<NSURL> {
	return Observable<NSURL>.create { observer in
	  urls.forEach { url in
	    Alamofire.download(.GET, url, destination: destination)
	      .response(queue: self.concurrentQueue, completionHandler: { request, response, _, error in
	      	observer.on(.Next(destinationUrl))
	      }
	  }
}

download(["url1", "url2"])
	.serialize()
	.subscribeNext { destinationUrl in
		// ...
	}
```

**Comment by fpillet** [comment]
This is the purpose of the `concatElements` issue #6 I added. Please add to the discussion there, we can also discuss the naming of the operator.

**Comment by i-schuetz** [comment]
What about the use case of `serialize` to handle multi threaded access?

**Comment by freak4pc** [comment]
Hey @i-schuetz, this is a 4 year old thread :) 
Please open a new issue if you have a suggestion/request.

Thanks!
